-- ESTRUCTURA GENERADA
CREATE TABLE departamentos (id_departamento INT AUTO_INCREMENT PRIMARY KEY, nombre_departamento VARCHAR(150) NOT NULL UNIQUE);
CREATE TABLE cargos (id_cargo INT AUTO_INCREMENT PRIMARY KEY, nombre_cargo VARCHAR(150) NOT NULL UNIQUE);
CREATE TABLE colaboradores (id_colaborador INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100), apellido VARCHAR(100), email VARCHAR(150), fecha_ingreso DATE, id_departamento INT, id_cargo INT, foto_ruta VARCHAR(255), FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento), FOREIGN KEY (id_cargo) REFERENCES cargos(id_cargo));

-- DATOS MAESTROS
INSERT INTO departamentos (nombre_departamento) VALUES ('CAMARA DE RESOLUCION');
INSERT INTO departamentos (nombre_departamento) VALUES ('COMISION DE ARBITROS');
INSERT INTO departamentos (nombre_departamento) VALUES ('COMISION DE ETICA');
INSERT INTO departamentos (nombre_departamento) VALUES ('COMISION DE FINANZAS');
INSERT INTO departamentos (nombre_departamento) VALUES ('COMISION MEDICA');
INSERT INTO departamentos (nombre_departamento) VALUES ('COMPENSACIONES');
INSERT INTO departamentos (nombre_departamento) VALUES ('COMPETICIONES');
INSERT INTO departamentos (nombre_departamento) VALUES ('CONSEJO DE HONOR');
INSERT INTO departamentos (nombre_departamento) VALUES ('DIRECCION DE DESARROLLO');
INSERT INTO departamentos (nombre_departamento) VALUES ('DIRECCION DE MERC. Y COM. ESTRATEGICAS');
INSERT INTO departamentos (nombre_departamento) VALUES ('DIRECCIÓN DE SCOUTING');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE ADMINISTRACION');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE ADMINISTRACION DE CLUBES');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE AUDITORIA');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE COMERCIALIZACION');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE COMUNICACIONES');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE GESTION DE TALENTO');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE INFRAEST. Y MANTENIMIENTO');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE LICENCIA DE CLUBES');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE MERCADEO');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE OPERACIONES');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE ORGANIZACION Y PROCESOS');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE PROCURA');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE S.I.');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE SEGURIDAD');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE SELECCIONES');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA DE TECNOLOGIA');
INSERT INTO departamentos (nombre_departamento) VALUES ('GERENCIA LEGAL');
INSERT INTO departamentos (nombre_departamento) VALUES ('LIGA FUTSAL');
INSERT INTO departamentos (nombre_departamento) VALUES ('OFICIAL DE CUMPLIMIENTO E INTEGRIDAD');
INSERT INTO departamentos (nombre_departamento) VALUES ('PRESIDENCIA');
INSERT INTO departamentos (nombre_departamento) VALUES ('REGISTROS Y COMPETENCIAS');
INSERT INTO departamentos (nombre_departamento) VALUES ('SECRETARIA GENERAL');
INSERT INTO departamentos (nombre_departamento) VALUES ('VICEPRESIDENCIA');
INSERT INTO cargos (nombre_cargo) VALUES ('ABOGADO');
INSERT INTO cargos (nombre_cargo) VALUES ('ABOGADO JUNIOR');
INSERT INTO cargos (nombre_cargo) VALUES ('ALMACENISTA');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA ADMINISTRATIVO');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA COMUNICACIONAL');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE ACTIVACIONES COMERCIALES');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE ACTIVACIONES DE PROYECTOS ESPECIALES');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE ACTIVOS FIJOS');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE CALIDAD DE VIDA');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE COMUNICACIONES SELECCIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE CONTROL DE GESTION');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE COOPERACION NAC .E INTER');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE DATOS - SCOUTING');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE GESTION DE ARBITROS');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE GESTION DE DESARROLLO');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE INFRAESTRUCTURA');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE OPERACIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE SISTEMA COMET');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE TESORERIA');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA DE VIDEO');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA OPERATIVO');
INSERT INTO cargos (nombre_cargo) VALUES ('ANALISTA SOPORTE TECNICO');
INSERT INTO cargos (nombre_cargo) VALUES ('APRENDIZ INCES');
INSERT INTO cargos (nombre_cargo) VALUES ('ASISTENTE');
INSERT INTO cargos (nombre_cargo) VALUES ('ASISTENTE DE PROGRAMACION');
INSERT INTO cargos (nombre_cargo) VALUES ('ASISTENTE DEL SEGUNDO VICEPRESIDENTE');
INSERT INTO cargos (nombre_cargo) VALUES ('ASISTENTE LEGAL');
INSERT INTO cargos (nombre_cargo) VALUES ('AUDIOVISUAL');
INSERT INTO cargos (nombre_cargo) VALUES ('AUDITOR JUNIOR');
INSERT INTO cargos (nombre_cargo) VALUES ('AUDITOR SENIOR');
INSERT INTO cargos (nombre_cargo) VALUES ('AUXILIAR ADMINISTRATIVO');
INSERT INTO cargos (nombre_cargo) VALUES ('AUXILIAR DE LIGA FUTSAL');
INSERT INTO cargos (nombre_cargo) VALUES ('AUXILIAR DE OPERACIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('AUXILIAR DE PROCURA');
INSERT INTO cargos (nombre_cargo) VALUES ('AUXILIAR DE REDES');
INSERT INTO cargos (nombre_cargo) VALUES ('AUXILIAR DE SEGURIDAD');
INSERT INTO cargos (nombre_cargo) VALUES ('CHOFER');
INSERT INTO cargos (nombre_cargo) VALUES ('CONSULTOR DE IMPUESTO');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR ADMINISTRATIVO');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE ACTIVACIONES COMERCIALES');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE ACTIVOS FIJOS');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE ALMACEN');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE CATEGORIAS MENORES MASCULINAS');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE COMUNICACIONES INSTITUCIONALES');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE COMUNICACIONES SELECCIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE CONSEJO DE HONOR');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE CONTABILIDAD');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE CONTROL ADMINISTRATIVO DE CLUBES');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE LOGISTICA DE ARBITROS');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE MARCA');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE PROCURA');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE PROYECTOS ESPECIALES');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE SCOUTING');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE SELECCIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DE TESORERIA');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR DEPORTIVO SELEC. FUTSAL Y FUTBOL PLAYA');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR II');
INSERT INTO cargos (nombre_cargo) VALUES ('COORDINADOR OPERATIVO DE SELECCIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('DIRECTOR DE MERCADEO Y COMUNICACIONES ESTRATEGICAS');
INSERT INTO cargos (nombre_cargo) VALUES ('DIRECTOR DE SCOUTING');
INSERT INTO cargos (nombre_cargo) VALUES ('DIRECTORA DE DESPACHO DE PRESIDENCIA');
INSERT INTO cargos (nombre_cargo) VALUES ('DISEÑADOR GRAFICO');
INSERT INTO cargos (nombre_cargo) VALUES ('ENFERMERA');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA - OJEADOR');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA CONTABLE');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE ATRACCION Y MOV. DE TALENTOS');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE COMPENSACIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE COMPETICIONES DE ALTO RENDIMIENTO');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE COMUNICACIONES DIGITALES');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE COMUNICACIONES INSTITUCIONAL');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE COMUNICACIONES SELECCIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE COMUNICACIONES, DIGITAL Y EVENTOS');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE CONSEJO DE HONOR');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE CONTROL DE GESTION');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE CONTROL DE GESTION DE SELECCIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE COOP. NACIONAL E INTERNACIONAL');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE DESARROLLO DE CAPACIDADES');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE FINANZAS');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE FORMACION Y DESARROLLO');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE FUTBOL AMATEUR');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE GESTION COMERCIAL');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE GESTION DE ARBITRAJE');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE GESTION INTEGRAL');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE LICENCIA DE ENTRENADORES');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE LIGA FUTBOL SALA');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE OPERACIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE ORGANIZACIÓN Y PROCESOS');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE PROCURA');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE REGISTRO Y COMPETENCIAS');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE SEG Y SALUD LABORAL');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE SEGURIDAD');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA DE SEGURIDAD DE LA INFORMACION');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA INSTITUCIONAL Y CONTROL');
INSERT INTO cargos (nombre_cargo) VALUES ('ESPECIALISTA LEGAL');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE ADMINISTRATIVO DE CLUBES');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE COMERCIAL');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE ADMINISTRACION');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE AUDITORIA');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE COMUNICACIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE DIVISION DE MERCADEO');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE FUTBOL AMATEUR');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE FUTBOL DE ALTO RENDIMIENTO');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE GESTION DE TALENTO');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE MANTENIMIENTO E INFRAESTRUCTURA');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE OPERACIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE ORGANIZACIÓN Y PROCESOS');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE PROCURA');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE SEGURIDAD');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE SEGURIDAD DE LA INFORMACION');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE DE TECNOLOGIA');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE LICENCIA DE CLUBES');
INSERT INTO cargos (nombre_cargo) VALUES ('GERENTE VAR - ARBITROS');
INSERT INTO cargos (nombre_cargo) VALUES ('INSPECTOR DE CLUBES');
INSERT INTO cargos (nombre_cargo) VALUES ('INSTRUCTOR DE ARBITROS');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE ADMINISTRACION DE PERSONAL');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE ALIANZAS COMERCIALES');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE ASOCIACIONES REGIONALES');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE CONTROL DE GESTION DE COMPETICIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE DESARROLLO');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE DESARROLLO TECNICO');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE EVALUACION DE IMPACTO');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE GESTION');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE LIGA FUTBOL SALA');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE MANTENIMIENTO E INFRAESTRUCTURA');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE MARCAS Y PROPIEDAD INTELECTUAL');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE ORGANO DE COMISIONES');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER DE PROGRAMAS DE DESARROLLO');
INSERT INTO cargos (nombre_cargo) VALUES ('LIDER OFICIAL DE CLUBES');
INSERT INTO cargos (nombre_cargo) VALUES ('MEDICO OCUPACIONAL');
INSERT INTO cargos (nombre_cargo) VALUES ('MEDICO TRAUMATOLOGO ORTOPEDISTA');
INSERT INTO cargos (nombre_cargo) VALUES ('MENSAJERO');
INSERT INTO cargos (nombre_cargo) VALUES ('NUTRICIONISTA');
INSERT INTO cargos (nombre_cargo) VALUES ('OFICIAL DE CUMPLIMIENTO E INTEGRIDAD');
INSERT INTO cargos (nombre_cargo) VALUES ('OFICIAL DE SEGURIDAD');
INSERT INTO cargos (nombre_cargo) VALUES ('OPERADOR DE SISTEMA COMET');
INSERT INTO cargos (nombre_cargo) VALUES ('PREPARADOR FISICO');
INSERT INTO cargos (nombre_cargo) VALUES ('PROJECT MANAGER');
INSERT INTO cargos (nombre_cargo) VALUES ('PROTOCOLO');
INSERT INTO cargos (nombre_cargo) VALUES ('RECEPCIONISTA');
INSERT INTO cargos (nombre_cargo) VALUES ('SECRETARIA');
INSERT INTO cargos (nombre_cargo) VALUES ('SECRETARIA DE DECISION DE COMISIÓN DE ÉTICA');
INSERT INTO cargos (nombre_cargo) VALUES ('SECRETARIA DE INSTRUCCION DE COMISION DE ETICA');
INSERT INTO cargos (nombre_cargo) VALUES ('SECRETARIA EJECUTIVA');
INSERT INTO cargos (nombre_cargo) VALUES ('SECRETARIA EJECUTIVA CONSEJO DE HONOR');
INSERT INTO cargos (nombre_cargo) VALUES ('SECRETARIA GENERAL ADJUNTA');
INSERT INTO cargos (nombre_cargo) VALUES ('SECRETARIO EJECUTIVO');
INSERT INTO cargos (nombre_cargo) VALUES ('SECRETARIO GENERAL');
INSERT INTO cargos (nombre_cargo) VALUES ('SUB OFICIAL DE CUMPLIMIENTO E INTEGRIDAD');
INSERT INTO cargos (nombre_cargo) VALUES ('SUPERVISOR REGISTROS Y COMPETENCIAS');
INSERT INTO cargos (nombre_cargo) VALUES ('TECNICO DE MANTENIMIENTO');
INSERT INTO cargos (nombre_cargo) VALUES ('TRAINER');
INSERT INTO cargos (nombre_cargo) VALUES ('UTILERO');

-- DATOS DE COLABORADORES
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YEFERSON', 'BALZA', 'yeferson.balza@fvf.com.ve', '2018-07-19', 12, 5, 'yeferson_balza.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DAGLIS', 'BARRETO', 'daglis.barreto@fvf.com.ve', '2020-01-01', 2, 23, 'daglis_barreto.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOHEL', 'BASTIDAS', 'johel.bastidas@fvf.com.ve', '2015-01-12', 8, 4, 'johel_bastidas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('AMARILIS', 'BELISARIO', 'amarilis.belisario@fvf.com.ve', '1999-07-19', 31, 146, 'amarilis_belisario.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('SOLANGE', 'BRICEÑO', 'solange.briceno@fvf.com.ve', '1996-02-08', 8, 25, 'solange_briceño.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('KARLEIDYS', 'CABEZA', 'karleidys.cabeza@fvf.com.ve', '2016-01-25', 17, 141, 'karleidys_cabeza.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ANA', 'CABRERA', 'ana.cabrera@fvf.com.ve', '2020-02-16', 32, 19, 'ana_cabrera.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MANUEL', 'CASTILLO', 'manuel.castillo@fvf.com.ve', '2020-02-16', 27, 59, 'manuel_castillo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ORIANA', 'DAVILA', 'oriana.davila@fvf.com.ve', '2017-12-12', 25, 37, 'oriana_davila.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YOSELING', 'DIAZ', 'yoseling.diaz@fvf.com.ve', '2006-02-15', 26, 25, 'yoseling_diaz.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('PEDRO', 'GOMEZ', 'pedro.gomez@fvf.com.ve', '2017-01-11', 2, 15, 'pedro_gomez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSE', 'GONZALEZ', 'joseignacio.fratini@fvf.com.ve', '2018-06-01', 19, 113, 'jose_gonzalez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DAVID', 'HUERTA', 'david.huerta@fvf.com.ve', '2014-06-23', 8, 75, 'david_huerta.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YOLIMAR', 'JULIO', 'yolimar.teran@fvf.com.ve', '2019-09-01', 2, 25, 'yolimar_julio.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('PADELIT', 'LEAL', 'padelit.leal@fvf.com.ve', '2016-08-03', 17, 10, 'padelit_leal.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YOANI', 'LINARES', 'yoani.linares@fvf.com.ve', '2019-03-07', 12, 20, 'yoani_linares.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('AUDEMIZ', 'MAIZO', 'audemiz.maizo@fvf.com.ve', '2018-11-12', 12, 41, 'audemiz_maizo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('EGLY', 'NUÑEZ', 'egly.nunez@fvf.com.ve', '2002-10-08', 32, 137, 'egly_nuñez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ANDREINA', 'PELAEZ', 'andreina.pelaez@fvf.com.ve', '2018-11-15', 9, 124, 'andreina_pelaez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('GERALDINE', 'RAMIREZ', 'geraldine.ramirez@fvf.com.ve', '2014-04-01', 8, 4, 'geraldine_ramirez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('KEVIN', 'RODRIGUEZ', 'kevin.rodriguez@fvf.com.ve', '2019-02-19', 12, 57, 'kevin_rodriguez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSMIR', 'RODRIGUEZ', 'josmir.rodriguez@fvf.com.ve', '2018-10-01', 2, 4, 'josmir_rodriguez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YUSANNY', 'ROJAS', 'yusanny.rojas@fvf.com.ve', '2016-03-09', 32, 91, 'yusanny_rojas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JORMAN', 'SALAZAR', 'jorman.salazar@fvf.com.ve', '2018-04-16', 25, 93, 'jorman_salazar.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JESUS', 'SANCHEZ', 'jesus.sanchez@fvf.com.ve', '2019-05-29', 9, 122, 'jesus_sanchez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('WILMAN', 'SANCHEZ', 'wilman.sanchez@fvf.com.ve', '2018-10-04', 27, 112, 'wilman_sanchez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('HEIDY', 'TINEO', NULL, '2010-06-01', 17, 141, 'heidy_tineo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('IRMA', 'TORRES', 'irmayovira.torres@fvf.com.ve', '2010-08-03', 29, 25, 'irma_torres.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YEIKAR', 'UZCATEGUI', 'yeikar.uzcategui@fvf.com.ve', '2019-05-29', 12, 12, 'yeikar_uzcategui.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('RAFAEL', 'VELASQUEZ', 'rafael.velasquez@fvf.com.ve', '2019-04-01', 27, 40, 'rafael_velasquez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOHN', 'ROTJES', 'john.rotjes@fvf.com.ve', '2020-09-01', 33, 119, 'john_rotjes.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ANGEL', 'SOTELDO', 'angel.soteldo@fvf.com.ve', '2020-09-01', 18, 17, 'angel_soteldo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('GUSTAVO', 'MACHADO', 'gustavo.machado@fvf.com.ve', '2020-09-01', 21, 18, 'gustavo_machado.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YONESKY', 'ARTEAGA', NULL, '2020-09-01', 17, 141, 'yonesky_arteaga.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSE', 'SALAS', 'jose.salas@fvf.com.ve', '2020-09-01', 2, 25, 'jose_salas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('KENNYS', 'NAVAS', 'kennys.navas@fvf.com.ve', '2020-11-01', 21, 3, 'kennys_navas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MARIA', 'ESPINOZA', 'fabiola.espinoza@fvf.com.ve', '2021-05-01', 9, 79, 'maria_espinoza.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('WILKERLIS', 'GIMENEZ', 'wilkerlis.gimenez@fvf.com.ve', '2021-07-26', 17, 81, 'wilkerlis_gimenez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ALBERTO', 'ANGULO', 'alberto.angulo@fvf.com.ve', '2021-07-07', 32, 151, 'alberto_angulo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JEAN', 'DURAN', 'jean.duran@fvf.com.ve', '2021-07-07', 25, 110, 'jean_duran.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('EVELIN', 'EVIES', 'evelin.evies@fvf.com.ve', '2021-07-07', 30, 135, 'evelin_evies.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JESUS', 'RAMOS', 'jesus.ramos@fvf.com.ve', '2021-07-07', 12, 99, 'jesus_ramos.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('SABRINA', 'SUAREZ', 'sabrina.suarez@fvf.com.ve', '2021-07-07', 33, 147, 'sabrina_suarez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('GUILLERMO', 'CEDANO', 'guillermo.cedano@fvf.com.ve', '2021-07-12', 17, 105, 'guillermo_cedano.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YUKENCY', 'MEJIA', 'yukency.mejia@fvf.com.ve', '2021-08-02', 17, 117, 'yukency_mejia.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DAVID', 'QUINTANILLA', 'david.quintanilla@fvf.com.ve', '2021-07-07', 33, 149, 'david_quintanilla.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('TAYLOR', 'RODRIGUEZ', 'taylor.rodriguez@fvf.com.ve', '2021-07-01', 7, 103, 'taylor_rodriguez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DANIEL', 'MARTINEZ', 'daniel.martinez@fvf.com.ve', '2021-07-01', 16, 73, 'daniel_martinez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ADDRIX', 'DELGADO', 'addrix.delgado@fvf.com.ve', '2021-07-01', 16, 47, 'addrix_delgado.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('REYNER', 'CLEMENTE', 'reyner.clemente@fvf.com.ve', '2021-07-01', 26, 56, 'reyner_clemente.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSE', 'NAVARRO', 'jose.navarro@fvf.com.ve', '2021-08-09', 23, 109, 'jose_navarro.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MANUEL', 'VIRGUEZ', 'manuel.virguez@fvf.com.ve', '2021-07-07', 26, 56, 'manuel_virguez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('BEIKER', 'RAMIREZ', 'adrian.ramirez@fvf.com.ve', '2021-07-01', 16, 29, 'beiker_ramirez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('SIMON', 'BARDINET', 'simon.bardinet@fvf.com.ve', '2021-07-01', 16, 29, 'simon_bardinet.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('FRANJOLYS', 'BORGES', 'franjolys.borges@fvf.com.ve', '2021-07-01', 29, 74, 'franjolys_borges.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('REBECA', 'MELO', 'rebeca.melo@fvf.com.ve', '2021-07-01', 20, 52, 'rebeca_melo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('HELEXANDRA', 'MARCANO', 'helexandra.marcano@fvf.com.ve', '2021-07-07', 31, 63, 'helexandra_marcano.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ANDRES', 'PIÑA', 'apinadreyer@fvf.com.ve', '2021-09-22', 33, 139, 'andres_piña.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LUIS', 'ALVAREZ', 'luis.alvarez@fvf.com.ve', '2021-09-27', 21, 107, 'luis_alvarez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ANTHONY', 'NAVAS', 'anthony.navas@fvf.com.ve', '2021-10-13', 21, 44, 'anthony_navas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YACKELYN', 'RONDON', 'atencionmedica@fvf.com.ve', '2021-10-20', 17, 65, 'yackelyn_rondon.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MARA', 'JIMENEZ', NULL, '2021-10-18', 3, 143, 'mara_jimenez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YANELSY', 'ARENAS', 'yanelsy.arenas@fvf.com.ve', '2021-09-20', 34, 142, 'yanelsy_arenas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ROBERT', 'MENDEZ', NULL, '2021-07-07', 5, 132, 'robert_mendez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('HILDEMAR', 'AGUERO', NULL, '2021-07-07', 26, 154, 'hildemar_aguero.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CARLOS', 'GARCIA', 'carlos.garcia@fvf.com.ve', '2021-11-08', 8, 148, 'carlos_garcia.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JUAN', 'TORRES', 'juan.torres@fvf.com.ve', '2021-08-12', 29, 22, 'juan_torres.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ISIS', 'VILLASMIL', 'isis.villasmil@fvf.com.ve', '2021-08-12', 29, 6, 'isis_villasmil.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DANIEL', 'LIMA', NULL, '2021-08-01', 26, 78, 'daniel_lima.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CARLOS', 'SALAZAR', NULL, '2021-07-07', 26, 154, 'carlos_salazar.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('SOR', 'RIVAS', 'sor.rivas@fvf.com.ve', '2021-07-07', 26, 134, 'sor_rivas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LORENA', 'ESCALONA', 'lorena.escalona@fvf.com.ve', '2021-12-06', 12, 39, 'lorena_escalona.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ZULAY', 'BORJAS', 'zulay.borjas@fvf.com.ve', '2021-11-01', 2, 138, 'zulay_borjas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('NICOLAS', 'CHAPARRO', 'nicolas.chaparro@fvf.com.ve', '2022-01-11', 11, 21, 'nicolas_chaparro.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LUIS', 'SANCHEZ', 'luisangel.sanchez@fvf.com.ve', '2022-01-10', 11, 62, 'luis_sanchez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSE', 'RIVAS', 'jose.rivas@fvf.com.ve', '2022-01-11', 11, 55, 'jose_rivas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DEISY', 'PEREZ', 'deisy.perez@fvf.com.ve', '2022-01-10', 32, 19, 'deisy_perez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DIEGO', 'CRISTALDO', 'diego.cristaldo@fvf.com.ve', '2022-01-03', 10, 61, 'diego_cristaldo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('FREDERICK', 'MENDEZ', 'frederick.mendez@fvf.com.ve', '2022-01-03', 9, 86, 'frederick_mendez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('PEDRO', 'ACOSTA', 'pedro.acosta@fvf.com.ve', '2022-01-11', 11, 66, 'pedro_acosta.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MILAGROS', 'RODRIGUEZ', 'milagros.rodriguez@fvf.com.ve', '2022-01-10', 32, 19, 'milagros_rodriguez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('VICENTE', 'ONORATO', 'vicente.onorato@fvf.com.ve', '2022-02-15', 16, 64, 'vicente_onorato.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('RODRIGO', 'LUGO', 'rodrigo.lugo@fvf.com.ve', '2022-02-14', 26, 60, 'rodrigo_lugo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LINO', 'MARTINEZ', 'lino.martinez@fvf.com.ve', '2022-02-21', 5, 132, 'lino_martinez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JEFFERSON', 'REAÑO', 'jefferson.reano@fvf.com.ve', '2022-02-21', 16, 64, 'jefferson_reaño.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MILEIDY', 'ROJAS', 'mileidy.rojas@fvf.com.ve', '2022-02-17', 22, 108, 'mileidy_rojas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('REINALDO', 'GALLEGO', 'reinaldo.gallego@fvf.com.ve', '2022-03-14', 6, 69, 'reinaldo_gallego.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JEFFERSON', 'DIAZ', 'jefferson.diaz@fvf.com.ve', '2022-03-09', 14, 100, 'jefferson_diaz.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MARIA', 'CISNEROS', 'maria.cisneros@fvf.com.ve', '2022-03-14', 22, 89, 'maria_cisneros.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('HUMBERTO', 'ARAUJO', 'humberto.araujo@fvf.com.ve', '2022-04-07', 21, 34, 'humberto_araujo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('GIOVANNY', 'DIAZ', NULL, '2022-04-08', 25, 136, 'giovanny_diaz.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ERMIDES', 'GUERE', 'ermides.guere@fvf.com.ve', '2022-04-18', 26, 45, 'ermides_guere.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YUSMEI', 'PATIÑO', NULL, '2022-04-12', 17, 141, 'yusmei_patiño.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('SULY', 'MORALES', 'suly.morales@fvf.com.ve', '2022-05-04', 17, 68, 'suly_morales.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ESCARLY', 'MAESTRE', 'escarly.maestre@fvf.com.ve', '2022-05-03', 26, 13, 'escarly_maestre.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('RICHARD', 'GARCIA', NULL, '2022-04-25', 28, 133, 'richard_garcia.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MARIBEL', 'DE PONTE', 'maribel.deponte@fvf.com.ve', '2022-05-24', 12, 5, 'maribel_de_ponte.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('VANESSA', 'RODRIGUEZ', 'vanessa.rodriguez@fvf.com.ve', '2022-06-01', 21, 95, 'vanessa_rodriguez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CLAUDIA', 'ESCALONA', 'claudia.escalona@fvf.com.ve', '2022-06-08', 13, 97, 'claudia_escalona.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LIZCELIS', 'GRATEROL', 'lizcelis.graterol@fvf.com.ve', '2022-06-08', 12, 5, 'lizcelis_graterol.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ANGEL', 'COCHO', 'angel.cocho@fvf.com.ve', '2022-05-24', 12, 49, 'angel_cocho.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YASMELY', 'SOLER', 'yasmely.soler@fvf.com.ve', '2022-06-13', 22, 89, 'yasmely_soler.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JESUS', 'RODRIGUES', 'jesus.rodrigues@fvf.com.ve', '2022-06-14', 16, 11, 'jesus_rodrigues.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MANUEL', 'TRUJILLO', 'manuel.trujillo@fvf.com.ve', '2022-06-01', 19, 115, 'manuel_trujillo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSE', 'BENCOMO', 'joseignacio.bencomo@fvf.com.ve', '2022-07-11', 9, 122, 'jose_bencomo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('PEDRO', 'SANDOVAL', 'pedro.sandoval@fvf.com.ve', '2022-08-09', 23, 53, 'pedro_sandoval.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MARIA', 'PALACIOS', 'maria.palacios@fvf.com.ve', '2022-08-01', 1, 145, 'maria_palacios.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CLARA', 'GONZALEZ', 'clara.gonzalez@fvf.com.ve', '2022-08-04', 16, 29, 'clara_gonzalez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('FRANCIS', 'URDANETA', 'francis.urdaneta@fvf.com.ve', '2022-07-18', 23, 35, 'francis_urdaneta.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ESTRELLA', 'VILLARROEL', 'estrella.villarroel@fvf.com.ve', '2022-07-18', 12, 32, 'estrella_villarroel.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YULIETT', 'BRICEÑO', 'yuliett.briceno@fvf.com.ve', '2022-07-18', 21, 34, 'yuliett_briceño.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ALEXANDER', 'CHOEZ', 'alexander.choez@fvf.com.ve', '2022-09-05', 27, 36, 'alexander_choez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YISEL', 'GONZALEZ', 'yisel.gonzalez@fvf.com.ve', '2022-09-05', 12, 20, 'yisel_gonzalez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('VICTOR', 'LEDEZMA', 'victor.ledezma@fvf.com.ve', '2022-09-05', 9, 121, 'victor_ledezma.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MILUSKA', 'LUGO', 'miluska.lugo@fvf.com.ve', '2022-09-08', 15, 42, 'miluska_lugo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOELY', 'CANELON', 'joely.canelon@fvf.com.ve', '2022-09-20', 30, 150, 'joely_canelon.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOHEL', 'LOPEZ', 'johel.lopez@fvf.com.ve', '2022-10-10', 18, 106, 'johel_lopez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YULEIDY', 'YZQUIERDO', 'yuleidy.yzquierdo@fvf.com.ve', '2022-10-13', 22, 89, 'yuleidy_yzquierdo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOAN', 'YANEZ', 'joan.yanez@fvf.com.ve', '2022-10-13', 14, 30, 'joan_yanez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LUIS', 'PEREZ', 'luis.perez@fvf.com.ve', '2022-10-17', 14, 31, 'luis_perez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ALEJANDRO', 'JAUREGUI', 'alejandro.jauregui@fvf.com.ve', '2022-11-01', 27, 26, 'alejandro_jauregui.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CARLOS', 'MANEIRO', 'carlos.maneiro@fvf.com.ve', '2022-11-02', 15, 42, 'carlos_maneiro.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JULIO', 'OSORIO', 'julio.osorio@fvf.com.ve', '2022-11-07', 8, 48, 'julio_osorio.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('GABRIEL', 'SANANES', 'gabriel.sananes@fvf.com.ve', '2022-11-14', 26, 56, 'gabriel_sananes.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOHN', 'COLINA', 'john.colina@fvf.com.ve', '2022-11-16', 15, 98, 'john_colina.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LUIS', 'GARCIA', 'luis.garcia@fvf.com.ve', '2022-12-12', 18, 152, 'luis_garcia.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('HENRY', 'CASANOVA', NULL, '2022-12-28', 25, 136, 'henry_casanova.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('KAIRO', 'MEDINA', 'kairo.medina@fvf.com.ve', '2023-01-05', 9, 129, 'kairo_medina.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ANA', 'GONZALEZ', 'ana.gonzalez@fvf.com.ve', '2023-01-11', 7, 120, 'ana_gonzalez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSE', 'BOLIVAR', 'jose.bolivar@fvf.com.ve', '2023-01-16', 7, 104, 'jose_bolivar.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MERIAN', 'SILVA', 'merian.silva@fvf.com.ve', '2023-02-01', 16, 101, 'merian_silva.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MIGUEL', 'HURTADO', 'miguel.hurtado@fvf.com.ve', '2023-02-01', 28, 28, 'miguel_hurtado.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('GRECIA', 'LOBO', NULL, '2023-02-01', 3, 144, 'grecia_lobo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ADRIAN', 'RODRIGUEZ', 'adrian.rodriguez@fvf.com.ve', '2023-02-07', 13, 2, 'adrian_rodriguez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LEONARDO', 'MORA', 'leonardo.mora@fvf.com.ve', '2023-02-09', 15, 118, 'leonardo_mora.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('FRANCIS', 'ROJAS', NULL, '2023-02-10', 26, 154, 'francis_rojas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ERNESTO', 'BRAUN', 'ernesto.braun@fvf.com.ve', '2023-03-01', 7, 88, 'ernesto_braun.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('OSCAR', 'AVENDAÑO', 'ernesto.braun@fvf.com.ve', '2023-03-06', 12, 67, 'oscar_avendaño.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JHONNY', 'RUBIO', NULL, '2023-03-06', 26, 154, 'jhonny_rubio.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ALBERTO', 'JASPE', NULL, '2023-03-20', 25, 136, 'alberto_jaspe.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ISABELLA', 'RAMIREZ', 'isabella.ramirez@fvf.com.ve', '2023-03-20', 15, 83, 'isabella_ramirez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('RAMON', 'SUAREZ', 'ramon.suarez@fvf.com.ve', '2023-03-13', 26, 21, 'ramon_suarez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JUAN', 'LONDOÑO', 'juan.londono@fvf.com.ve', '2023-03-15', 26, 21, 'juan_londoño.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DANNY', 'PADRON', NULL, '2023-03-21', 26, 154, 'danny_padron.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YEISA', 'RIVAS', 'yeisa.adonay@fvf.com.ve', '2023-04-10', 23, 90, 'yeisa_rivas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YOFRAN', 'PERDOMO', 'yofran.perdomo@fvf.com.ve', '2023-04-10', 7, 82, 'yofran_perdomo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('IVANNA', 'FRESAN', 'ivanna.fresan@fvf.com.ve', '2023-05-02', 33, 128, 'ivanna_fresan.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JHONDY', 'MANCERA', 'jhonddy.mancera@fvf.com.ve', '2023-05-02', 29, 125, 'jhondy_mancera.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('REYNALDO', 'VERENZUELA', 'reynaldo.verenzuela@fvf.com.ve', '2023-06-13', 2, 84, 'reynaldo_verenzuela.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('GABRIEL', 'BASTIDAS', 'gabriel.bastidas@fvf.com.ve', '2023-07-25', 33, 1, 'gabriel_bastidas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ADRIANA', 'SAYAGO', 'adriana.sayago@fvf.com.ve', '2023-08-07', 1, 1, 'adriana_sayago.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LUISBERT', 'OMAÑA', 'luisbert.omana@fvf.com.ve', '2023-08-14', 12, 43, 'luisbert_omaña.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('HORACIO', 'COBOS', 'horacio.cobos@fvf.com.ve', '2023-09-04', 23, 90, 'horacio_cobos.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JEFERSON', 'AREVALO', 'jeferson.arevalo@fvf.com.ve', '2023-10-02', 12, 9, 'jeferson_arevalo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DEIVIS', 'MONTILLA', 'deivis.montilla@fvf.com.ve', '2023-10-16', 18, 126, 'deivis_montilla.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ALEX', 'CANDIALES', 'alex.candiales@fvf.com.ve', '2023-10-19', 13, 50, 'alex_candiales.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('GIOMAR', 'MORAN', 'giomar.moran@fvf.com.ve', '2023-11-09', 4, 80, 'giomar_moran.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('KITSBELY', 'ROJAS', 'kitsbely.rojas@fvf.com.ve', '2023-11-13', 7, 70, 'kitsbely_rojas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LUIS', 'PERDOMO', 'luis.perdomo@fvf.com.ve', '2023-11-15', 2, 51, 'luis_perdomo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MARTIN', 'MALDONADO', 'martin.maldonado@fvf.com.ve', '2023-12-01', 9, 16, 'martin_maldonado.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JESUS', 'GONZALEZ', NULL, '2023-12-06', 17, 24, 'jesus_gonzalez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('SCARLY', 'ROA', NULL, '2023-12-06', 17, 24, 'scarly_roa.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('EDUARD', 'BLANCO', NULL, '2023-12-06', 17, 24, 'eduard_blanco.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CESAR', 'MIJARES', NULL, '2023-12-06', 17, 24, 'cesar_mijares.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('BRAYENNIS', 'GRATEROL', NULL, '2023-12-06', 17, 24, 'brayennis_graterol.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JANNY', 'ARAUJO', NULL, '2023-12-06', 17, 24, 'janny_araujo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('BRENDALY', 'ORTIGA', NULL, '2023-12-06', 17, 24, 'brendaly_ortiga.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DUGLIANNY', 'ARGUELLO', NULL, '2023-12-06', 17, 24, 'duglianny_arguello.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('REIBER', 'ORTEGA', NULL, '2023-12-06', 17, 24, 'reiber_ortega.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSCAR', 'FIGUEROA', NULL, '2023-12-06', 17, 24, 'joscar_figueroa.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CRISLEIDI', 'TORO', NULL, '2023-12-06', 17, 24, 'crisleidi_toro.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LUIS', 'GUTIERREZ', 'luis.gutierrez@fvf.com.ve', '2024-02-14', 26, 77, 'luis_gutierrez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('RAUL', 'LORETO', 'atencionmedica@fvf.com.ve', '2024-02-26', 17, 131, 'raul_loreto.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSE', 'LAYA', NULL, '2024-02-01', 26, 154, 'jose_laya.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSE', 'GINART', 'jose.ginart@fvf.com.ve', '2024-03-11', 11, 14, 'jose_ginart.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CRISMARYS', 'CEDEÑO', 'crismarys.cedeno@fvf.com.ve', '2024-03-11', 15, 54, 'crismarys_cedeño.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MICHELLE', 'BARRIOS', NULL, '2024-04-08', 17, 24, 'michelle_barrios.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('VERONICA', 'PEREZ', 'veronica.perez@fvf.com.ve', '2024-05-02', 26, 60, 'veronica_perez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YILBER', 'CASTELLANO', 'yilber.castellano@fvf.com.ve', '2024-05-13', 23, 76, 'yilber_castellano.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('LUZ', 'JIMENEZ', 'luz.jimenez@fvf.com.ve', '2024-05-20', 29, 87, 'luz_jimenez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JOSE', 'PERDOMO', 'jose.perdomo@fvf.com.ve', '2024-07-15', 24, 111, 'jose_perdomo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CARLOS', 'SEGUERI', 'carlos.segueri@fvf.com.ve', '2024-06-01', 29, 56, 'carlos_segueri.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ANA', 'NOVA', 'ana.nova@fvf.com.ve', '2024-08-05', 24, 94, 'ana_nova.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('BRAYHAN', 'JIMENEZ', 'brayhan.jimenez@fvf.com.ve', '2024-08-05', 26, 56, 'brayhan_jimenez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CLAUDIA', 'BREDA', 'claudia.breda@fvf.com.ve', '2024-09-02', 28, 127, 'claudia_breda.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MARIA', 'GUTIERREZ', NULL, '2024-09-02', 28, 27, 'maria_gutierrez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('GENESIS', 'GOMEZ', NULL, '2024-10-09', 17, 24, 'genesis_gomez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DELIMAR', 'RODRIGUEZ', NULL, '2024-10-09', 17, 24, 'delimar_rodriguez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ISABELLA', 'LUGO', NULL, '2024-10-09', 17, 24, 'isabella_lugo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('HILARY', 'GIL', NULL, '2024-10-09', 17, 24, 'hilary_gil.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YHONDEIBER', 'BRAVO', NULL, '2024-10-09', 17, 24, 'yhondeiber_bravo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('IVIANNYS', 'ROJAS', NULL, '2024-10-09', 17, 24, 'iviannys_rojas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CHRISTIAN', 'DELGADO', 'christian.delgado@fvf.com.ve', '2024-11-21', 16, 72, 'christian_delgado.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DIANA', 'VALLADARES', 'diana.valladares@fvf.com.ve', '2024-12-03', 19, 115, 'diana_valladares.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ALVIN', 'HARTING', 'gabriel.harting@fvf.com.ve', '2024-12-03', 20, 102, 'alvin_harting.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DANIELA', 'ALCALA', 'daniela.alcala@fvf.com.ve', '2025-01-15', 15, 8, 'daniela_alcala.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('HENRY', 'GOMEZ', 'henry.gomez@fvf.com.ve', '2025-01-20', 9, 123, 'henry_gomez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('FRANKLIN', 'PORRAS', 'franklin.porras@fvf.com.ve', '2025-01-20', 17, 92, 'franklin_porras.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JHON', 'ARCHER', 'jhon.archer@fvf.com.ve', '2025-03-05', 21, 38, 'jhon_archer.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('WILFREDO', 'GUARAMATO', 'wilfredo.guaramato@fvf.com.ve', '2025-03-17', 9, 79, 'wilfredo_guaramato.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('RICARDO', 'ANDREUTTI', 'ricardo.andreutti@fvf.com.ve', '2025-03-24', 7, 120, 'ricardo_andreutti.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ALEJANDRO', 'RONDON', 'alejandro.rondon@fvf.com.ve', '2025-04-02', 26, 58, 'alejandro_rondon.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('BRAYAN', 'APARICIO', 'brayan.aparicio@fvf.com.ve', '2025-04-07', 31, 140, 'brayan_aparicio.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('STEPHANNY', 'MEZA', 'stephanny.meza@fvf.com.ve', '2025-04-07', 31, 141, 'stephanny_meza.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CARLOS', 'GONZALEZ', 'carlos.gonzalez@fvf.com.ve', '2025-04-14', 29, 33, 'carlos_gonzalez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CARLOS', 'ARNEDO', 'carlos.arnedo@fvf.com.ve', '2025-05-05', 17, 153, 'carlos_arnedo.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('GABRIELA', 'PABON', NULL, '2025-05-05', 17, 141, 'gabriela_pabon.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CLAUDIA', 'BARELA', 'claudia.barela@fvf.com.ve', '2025-05-12', 33, 130, 'claudia_barela.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('PAULINA', 'PLACENCIA', NULL, '2025-05-19', 17, 141, 'paulina_placencia.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('STEFANO', 'OSUNA', 'stefano.osuna@fvf.com.ve', '2025-07-28', 11, 66, 'stefano_osuna.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('CARLOS', 'LOPEZ', 'carlos.lopez@fvf.com.ve', '2025-08-01', 2, 114, 'carlos_lopez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('JHON', 'CARDENAS', NULL, '2025-08-01', 26, 154, 'jhon_cardenas.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('ALEXIS', 'RENDON', 'alexis.rendon@fvf.com.ve', '2025-08-06', 2, 116, 'alexis_rendon.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('OSCAR', 'HERNANDEZ', 'oscar.hernandez@fvf.com.ve', '2025-08-18', 8, 96, 'oscar_hernandez.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('YATZURY', 'PALMERA', 'yatzury.palmera@fvf.com.ve', '2025-09-15', 15, 7, 'yatzury_palmera.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DANIELA', 'PALENCIA', 'daniela.palencia@fvf.com.ve', '2025-10-21', 16, 71, 'daniela_palencia.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('DOUGLEIDYS', 'FUENMAYOR', 'dougleidys.fuenmayor@fvf.com.ve', '2025-12-08', 12, 85, 'dougleidys_fuenmayor.jpg');
INSERT INTO colaboradores (nombre, apellido, email, fecha_ingreso, id_departamento, id_cargo, foto_ruta) VALUES ('MARIA', 'INNECCO', 'maria.innecco@fvf.com.ve', '2025-12-08', 16, 46, 'maria_innecco.jpg');
